# 数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_online?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  # 设置全局日期格式,如果设置这个格式,则代码中@DateTimeFormat(pattern = "dd/MM/yyyy") 无效!!
  mvc:
    format:
      date: yyyy-MM-dd

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

# Mybatis 配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.volcano.examonlineserv.mapper: debug




